services:
  redis:
    image: redis:8.2.2-alpine3.22
    ports:
      - "6379:6379"
  keygenerator:
    image: soserdev/shortener-keygenerator:latest  # Built from your Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
