services:
  redis:
    image: redis:8.2.2-alpine3.22
    ports:
      - "6379:6379"
  keygenerator:
    image: soserdev/shortener-keygenerator:latest  # Built from your Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  mongo:
    image: mongo:7.0.11
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    restart: unless-stopped
    depends_on:
      - keygenerator

  urlservice:
    image: soserdev/shortener-urlservice:latest
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      SPRING_MONGODB_HOST: mongo
    restart: unless-stopped